### ISSUE TITLE
Crash after update 

### ISSUE THREAD

**Issue by RaymondTracer** [CorruptedArk/did-i-take-my-meds#54] opened 2022-04-14 15:57 UTC
**Describe the bug**
The app crashes when I go into any one of my medications

**To Reproduce**
1. Open app
2. Tap medication
3. Crash

**Expected behavior**
The medication opens like normal.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 12
 - Version: 1.6.4
 - Build Location: F-Droid

**Additional context**
N/A

**Comment by CorruptedArk** [comment] 2022-04-14 16:00
This is fixed in 1.6.5

**Closed** 2022-04-14 16:00 UTC
Labels: bug, duplicate

**Comment by CorruptedArk** [comment] 2022-04-14 16:01
Duplicate of #53
