### ISSUE TITLE
Option to set a reminder for specific days.

### ISSUE THREAD

**Issue by mounteerie** [CorruptedArk/did-i-take-my-meds#5] opened 2021-07-28 12:48 UTC
**Is your feature request related to a problem? Please describe.**
I have multiple medications that I have to take on different days/times during the week. For example, I have to take one of my medications in the morning on one day and in the evening on another.

**Describe the solution you'd like**
1. An option to set a day (as well as time) for a medication reminder.
2. An option to have multiple days and times under one medication reminder.

**Comment by CorruptedArk** [comment] 2021-07-28 16:14
I'm currently working on functionality that is similar to this. 

In your case, are your doses on specific days of the week or do they repeat after a set number of days?

**Comment by mounteerie** [comment] 2021-07-29 03:40
In my case it's both. I have to take one medication at a specific time and day (eg. Monday evening, Friday morning). Another I have to take every second day.

**Comment by CorruptedArk** [comment] 2021-07-29 03:52
Alright, it's hard to do both in a clean way, but my current plan will allow for both. Basically, a medication will have multiple schedules. Each schedule has a time of day, a start date, and a set repeat period of at least a day. So in your case, for specific weekdays, you pick a start day on that day of week and you set the repeat for a week. For every other day, you set a repeat of 2 days and 0 weeks. It's a bit messy, but the problem is harder than you might think on the surface.

**Comment by CorruptedArk** [comment] 2021-08-09 03:22
This feature is now merged into master from the complex-times branch

**Closed by CorruptedArk** 2021-08-09 03:22 UTC
